### ISSUE TITLE
This code is still C

### ISSUE THREAD

**Issue by ice1000** [chuigda/vulkan4j#18]
https://github.com/chuigda/vulkan4j/blob/03e0849dced65e890fca2ab96bed4da3eff284b1/tutorial/mdbook/en/src/setup/validation-layers.md?plain=1#L17-L31

**Comment by chuigda** [comment]
This is the intended behavior since `vkCreateInstance` itself is a native function, and we're using native code to illustrate how this native function works internally. You may think that one reading this tutorial may not have experience on C programming, but a guy without C language basis is unlikely to be capable of learning the Vulkan API itself anyway.

**Comment by ice1000** [comment]
I see I see
